[package]
name = "verlet-balls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "*"
rand = { version = "*", features = ["small_rng"] }
lazy_static = "*"
